import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "@utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Link Shortener</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <div>
          <h1>Hello World!</h1>
          <div>
          </div>
        </div>
      </Head>
    </>
  );
};

export default Home;
